version: '3'

services:

  todotests:
    image: todotests
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      FRONT_HOST: todofront
      FRONT_PORT: 3000
    networks:
      - front-network

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - "todoback"
    environment:
      REACT_APP_API_HOST: todoback
      REACT_APP_API_PORT: 3001
    networks:
      - front-network
      - back-network

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - back-network

networks:
  front-network: {}
  back-network: {}
